[package]
name = "evm-state"
version = "0.1.0"
authors = ["Vladimir Motylenko <vld@stegos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evm = { version = "0.18", features = ["with-serde"] }
primitive-types = "0.7.2"
log="0.4"
simple_logger="1.11"
hex="0.4.2"
serde="1.0"
sha3="0.9.1"
assert_matches = "1.4"
rand = "0.7.3"
rlp="0.4.6"
secp256k1 = { version = "0.19.0", features = ["recovery", "global-context"]}
#force rand version, because 0.6.5 break compatibility with secp256k1
rand2={version="=0.6.1", package="rand"}

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_evm"
harness = false